import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppWrapper } from '@/context';
import Header from "@/components/header";
import HeaderMobile from "@/components/header-mobile";
import { Toaster } from 'react-hot-toast';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Solefy",
  description: "Generated by Solefy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='bg-[#f2f2f2]'>
        <AppWrapper>
          <Toaster />
          <Header />
          <HeaderMobile />
          {children}
        </AppWrapper>
      </body>

    </html>
  );
}
